### ISSUE TITLE
Configuration simplifiée

### ISSUE THREAD

**Issue by Nyxis** [LinkValue/MajoraOAuthServerBundle#20]
Ne pas avoir :

``` yml
# MajoraOAuthServerBundle
majora_oauth_server:
    secret: %secret%
    access_token:
        loader: { orm: ~ }
        repository: { orm: ~ }
    refresh_token:
        loader: { orm: ~ }
        repository: { orm: ~ }
    account:
        loader:
            id: axa.person.loader
        repository:
            id: axa.person.repository
    application:
        loader: { orm: ~ }
        repository: { orm: ~ }
```

Mais :

``` yml
# MajoraOAuthServerBundle
majora_oauth_server:
    secret: %secret%
    driver:
        orm: ~
    account:
        loader:
            id: axa.person.loader
        repository:
            id: axa.person.repository
```
